name: PnP Sample.json validation

on:
  pull_request_target:
    branches:
      - "main"

jobs:
  validate:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        uses: pnp/pnp-sample-validation@main
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
